/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appbancaria;


/**
 *
 * @author Yeraldi Treviño
 */



public class MainWindow extends javax.swing.JFrame {
     public MainWindow(){
          initComponents();
     }

/**
      * Creates new form MainWindow
      */
          /**
      * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          addClientBtm = new javax.swing.JButton();
          addEmployedBtm = new javax.swing.JButton();
          addSegmentBtm = new javax.swing.JButton();
          addPromoBtm = new javax.swing.JButton();
          addProductBtm = new javax.swing.JButton();
          moreOptionsBtm = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jLabel1.setText("Administrador de BDD Bancaria");

          addClientBtm.setText("Agregar Cliente");
          addClientBtm.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    addClientBtmMouseClicked(evt);
               }
          });

          addEmployedBtm.setText("Agregar Empleado");
          addEmployedBtm.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    addEmployedBtmMouseClicked(evt);
               }
          });

          addSegmentBtm.setText("Crear Segmento");
          addSegmentBtm.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    addSegmentBtmMouseClicked(evt);
               }
          });

          addPromoBtm.setText("Agregar Promocion");
          addPromoBtm.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    addPromoBtmMouseClicked(evt);
               }
          });

          addProductBtm.setText("Crear Producto");
          addProductBtm.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    addProductBtmMouseClicked(evt);
               }
          });

          moreOptionsBtm.setText("Otras Acciones");
          moreOptionsBtm.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    moreOptionsBtmMouseClicked(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(276, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(addClientBtm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(addEmployedBtm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(addSegmentBtm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(addPromoBtm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(addProductBtm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(moreOptionsBtm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(268, 268, 268))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)
                    .addComponent(addClientBtm)
                    .addGap(18, 18, 18)
                    .addComponent(addEmployedBtm)
                    .addGap(18, 18, 18)
                    .addComponent(addSegmentBtm)
                    .addGap(18, 18, 18)
                    .addComponent(addPromoBtm)
                    .addGap(18, 18, 18)
                    .addComponent(addProductBtm)
                    .addGap(18, 18, 18)
                    .addComponent(moreOptionsBtm)
                    .addContainerGap(103, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void addClientBtmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClientBtmMouseClicked
          // TODO add your handling code here:
          this.setVisible(false);
          AddClientWindow open = new AddClientWindow();
          open.setVisible(true);
     }//GEN-LAST:event_addClientBtmMouseClicked

     private void addEmployedBtmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployedBtmMouseClicked
          // TODO add your handling code here:
          this.setVisible(false);
          AddEmployedWindow open = new AddEmployedWindow();
          open.setVisible(true);
     }//GEN-LAST:event_addEmployedBtmMouseClicked

     private void addSegmentBtmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSegmentBtmMouseClicked
          // TODO add your handling code here:
          this.setVisible(false);
          AddSegmentWindow open = new AddSegmentWindow();
          open.setVisible(true);
     }//GEN-LAST:event_addSegmentBtmMouseClicked

     private void addPromoBtmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPromoBtmMouseClicked
          // TODO add your handling code here:
          this.setVisible(false);
          AddPromoWindow open = new AddPromoWindow();
          open.setVisible(true);
     }//GEN-LAST:event_addPromoBtmMouseClicked

     private void addProductBtmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductBtmMouseClicked
          // TODO add your handling code here:
          this.setVisible(false);
          AddProductWindow open = new AddProductWindow();
          open.setVisible(true);
     }//GEN-LAST:event_addProductBtmMouseClicked

     private void moreOptionsBtmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moreOptionsBtmMouseClicked
          // TODO add your handling code here:
          this.setVisible(false);
          moreOptionsWindow open = new moreOptionsWindow();
          open.setVisible(true);
     }//GEN-LAST:event_moreOptionsBtmMouseClicked

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new MainWindow().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton addClientBtm;
     private javax.swing.JButton addEmployedBtm;
     private javax.swing.JButton addProductBtm;
     private javax.swing.JButton addPromoBtm;
     private javax.swing.JButton addSegmentBtm;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JButton moreOptionsBtm;
     // End of variables declaration//GEN-END:variables
}
