/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appbancaria;

/**
 *
 * @author Yeraldi Treviño
 */
public class moreOptionsWindow extends javax.swing.JFrame {

     /**
      * Creates new form moreOptionsWindow
      */
     public moreOptionsWindow() {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          mainWindowBackBtm = new javax.swing.JButton();
          jLabel1 = new javax.swing.JLabel();
          btmClients = new javax.swing.JButton();
          btmEmployed = new javax.swing.JButton();
          btmSegment = new javax.swing.JButton();
          btmPromo = new javax.swing.JButton();
          btmProducto = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          mainWindowBackBtm.setText("Volver  A Menu Principal");
          mainWindowBackBtm.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    mainWindowBackBtmMouseClicked(evt);
               }
          });

          jLabel1.setText("Visualizacion De Datos");
          jLabel1.setToolTipText("");

          btmClients.setText("Clientes");
          btmClients.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    btmClientsMouseClicked(evt);
               }
          });

          btmEmployed.setText("Empleados");
          btmEmployed.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    btmEmployedMouseClicked(evt);
               }
          });

          btmSegment.setText("Segmentos");
          btmSegment.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    btmSegmentMouseClicked(evt);
               }
          });

          btmPromo.setText("Promociones");
          btmPromo.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    btmPromoMouseClicked(evt);
               }
          });

          btmProducto.setText("Productos");
          btmProducto.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    btmProductoMouseClicked(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(254, 254, 254)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(mainWindowBackBtm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(btmProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(btmPromo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(btmSegment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(btmEmployed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(btmClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addComponent(jLabel1)
                              .addGap(18, 18, 18)))
                    .addContainerGap(248, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btmClients)
                    .addGap(18, 18, 18)
                    .addComponent(btmEmployed)
                    .addGap(18, 18, 18)
                    .addComponent(btmSegment)
                    .addGap(18, 18, 18)
                    .addComponent(btmPromo)
                    .addGap(18, 18, 18)
                    .addComponent(btmProducto)
                    .addGap(18, 18, 18)
                    .addComponent(mainWindowBackBtm)
                    .addContainerGap(95, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void mainWindowBackBtmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainWindowBackBtmMouseClicked
          // TODO add your handling code here:
          this.setVisible(false);
          MainWindow open = new MainWindow();
          open.setVisible(true);
     }//GEN-LAST:event_mainWindowBackBtmMouseClicked

     private void btmClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmClientsMouseClicked
          // TODO add your handling code here:
          this.setVisible(false);
          ViewClientsWindow open = new ViewClientsWindow();
          open.setVisible(true);
     }//GEN-LAST:event_btmClientsMouseClicked

     private void btmEmployedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmEmployedMouseClicked
          // TODO add your handling code here:
          this.setVisible(false);
          ViewEmployedWindow open = new ViewEmployedWindow();
          open.setVisible(true);
     }//GEN-LAST:event_btmEmployedMouseClicked

     private void btmSegmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmSegmentMouseClicked
          // TODO add your handling code here:
          this.setVisible(false);
          ViewSegmentWindow open = new ViewSegmentWindow();
          open.setVisible(true);
     }//GEN-LAST:event_btmSegmentMouseClicked

     private void btmPromoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmPromoMouseClicked
          // TODO add your handling code here:
          this.setVisible(false);
          ViewPromoWindow open = new ViewPromoWindow();
          open.setVisible(true);
     }//GEN-LAST:event_btmPromoMouseClicked

     private void btmProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmProductoMouseClicked
          // TODO add your handling code here:
          this.setVisible(false);
          ViewProductWindow open = new ViewProductWindow();
          open.setVisible(true);
     }//GEN-LAST:event_btmProductoMouseClicked

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(moreOptionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(moreOptionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(moreOptionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(moreOptionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new moreOptionsWindow().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btmClients;
     private javax.swing.JButton btmEmployed;
     private javax.swing.JButton btmProducto;
     private javax.swing.JButton btmPromo;
     private javax.swing.JButton btmSegment;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JButton mainWindowBackBtm;
     // End of variables declaration//GEN-END:variables
}
