/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appbancaria;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yeraldi Treviño
 */
public class ViewEmployedWindow extends javax.swing.JFrame {
     private final String[] columnas = {"No Empleado", "Nombre", "Apellido",
        "Puesto", "Sueldo"};
     private DefaultTableModel tm = new DefaultTableModel(columnas, 0);
     /**
      * Creates new form ViewEmployedWindow
      */
     public ViewEmployedWindow() {
          initComponents();
          columnsNameGrid();
     }

     /**
      * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jScrollPane1 = new javax.swing.JScrollPane();
          EmployedTable = new javax.swing.JTable();
          jLabel1 = new javax.swing.JLabel();
          moreOptsBtm = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          EmployedTable.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null}
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
               }
          ));
          jScrollPane1.setViewportView(EmployedTable);

          jLabel1.setText("Visualizacion de Empleados Bancarios");

          moreOptsBtm.setText("Volver A Inicio");
          moreOptsBtm.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    moreOptsBtmMouseClicked(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap(71, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(moreOptsBtm, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(27, 27, 27))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addComponent(jLabel1)
                              .addGap(290, 290, 290))))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap(28, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addComponent(jLabel1)
                              .addGap(63, 63, 63)
                              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addComponent(moreOptsBtm)
                              .addGap(23, 23, 23))))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void moreOptsBtmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moreOptsBtmMouseClicked
          // TODO add your handling code here:
          this.setVisible(false);
          moreOptionsWindow open = new moreOptionsWindow();
          open.setVisible(true);
     }//GEN-LAST:event_moreOptsBtmMouseClicked
     
     private void columnsNameGrid() {
          Empleado employed = new Empleado();
          ResultSet rs = employed.viewEmployed();
          tm = new DefaultTableModel(columnas, 0);
          try {
               while (rs.next()) {
                    Object[] ob = {
                         rs.getInt("id_empleado"),
                         rs.getString("nombre"),
                         rs.getString("apellido"),
                         rs.getString("puesto"),
                         rs.getFloat("sueldo")
                    };
                    tm.addRow(ob);
                    EmployedTable.setModel(tm);
               }
          } catch (Exception e) {
               JOptionPane.showMessageDialog(null,"Error: "+ e);
          }
     }
     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(ViewEmployedWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(ViewEmployedWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(ViewEmployedWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(ViewEmployedWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new ViewEmployedWindow().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JTable EmployedTable;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JButton moreOptsBtm;
     // End of variables declaration//GEN-END:variables
}
